### ISSUE TITLE
Tests failing on Pi4

### ISSUE THREAD

**Issue by wimrijnders** [Idein/py-videocore6#40]
I followed the instructions to the letter on a Pi4 and I see all tests failing.
The output is quite length; I'll show the first and final part here:

```
Failure: ImportError (

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.18.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
) ... ERROR
Failure: ImportError (

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.18.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
) ... ERROR
Failure: ImportError (

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

...

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.18.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory


----------------------------------------------------------------------
Ran 12 tests in 0.154s

FAILED (errors=10)

uifcfg:       0x00000045
hub_ident1:   0x000e1124
hub_ident2:   0x00000100
hub_ident3:   0x00000e00
core0_ident0: 0x04443356
core0_ident1: 0x81001422
core0_ident2: 0x40078121
supports_tfu: 0x00000001
supports_csd: 0x00000001
Consult /sys/kernel/debug/dri/0/v3d_regs for more information

size    = 0x01000000
handle  = 0x00000001
phyaddr = 0x00020000
offset  = 0x10000000
```

**Comment by wimrijnders** [comment]
Following the link to the [troubleshooting page](https://numpy.org/devdocs/user/troubleshooting-importerror.html), I found the solution for the recurring error

```
libf77blas.so.3: cannot open shared object file: No such file or directory
```
The solution is either:

```
sudo apt-get install libatlas-base-dev
```

Or:

```
pip3 uninstall numpy  # remove previously installed version
apt install python3-numpy
```

I tried them both, both with the same result. The tests run now, but the final test appears to fail:

```
======================================================================
ERROR: test_v3d.test_v3d_regs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wim/projects/py-videocore6/dest/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/wim/projects/py-videocore6/tests/test_v3d.py", line 12, in test_v3d_regs
    with RegisterMapping() as regmap:
  File "/home/wim/projects/py-videocore6/videocore6/v3d.py", line 142, in __init__
    raise Exception('readwrite4 library is not found.'
Exception: readwrite4 library is not found. Your installation seems to be broken.

----------------------------------------------------------------------
Ran 38 tests in 12.369s

FAILED (errors=1)
```

**Comment by wimrijnders** [comment]
This looks like a missing dependency, but I'll await your feedback, me being a python noob and all.

**Comment by Terminus-IMRC** [comment]
Thank you for the report. We will correct the install instructions in the README.

As for the readwrite4 error, please run: `python3 setup.py build_ext --inplace`.

**Comment by wimrijnders** [comment]
OK thanks.

Using `sudo PYTHONPATH=dest nosetests -v -s` now runs perfectly.
Using the non-sudo version still fails. Is this what you would expect?

On 5/18/20, Yukimasa Sugizaki <notifications@github.com> wrote:
> Thank you for the report. We will correct the install instructions in the
> README.
>
> As for the readwrite4 error, please run: `python3 setup.py build_ext
> --inplace`.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Idein/py-videocore6/issues/40#issuecomment-630111745


-- 
Met vriendelijke groet,

Wim Rijnders
http://axizo.nl

**Comment by Terminus-IMRC** [comment]
What does the error say when without sudo?

**Comment by wimrijnders** [comment]
All tests fail with the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nose/case.py", line
198, in runTest
    self.test(*self.arg)
  File "/home/wim/projects/py-videocore6/tests/test_drm.py", line 8,
in test_get_param
    with DRM_V3D() as drm:
  File "/home/wim/projects/py-videocore6/videocore6/drm_v3d.py", line
11, in __init__
    self.fd = os.open(f'/dev/dri/card{n}', os.O_RDWR)
PermissionError: [Errno 13] Permission denied: '/dev/dri/card0'
```

On 5/18/20, Yukimasa Sugizaki <notifications@github.com> wrote:
> What does the error say when without sudo?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Idein/py-videocore6/issues/40#issuecomment-630116869


-- 
Met vriendelijke groet,

Wim Rijnders
http://axizo.nl

**Comment by Terminus-IMRC** [comment]
Thank you for the log. `/dev/dri/card0` is a device to communicate with the graphics hardware (V3D). You must be a root user or belong to `video` group. If you choose the latter, please run: `sudo usermod -a -G video $USER`.

**Comment by wimrijnders** [comment]
OK that makes sense.
Tried after running given command, after logging out and in the non-sudo tests also run perfectly.

_(If you are documenting this, please add the logout and login)_

**Comment by Terminus-IMRC** [comment]
I'm happy that it works on your pi!

Thank you for letting us know that the document is insufficient. To tell the truth we've not tested it on a bare raspbian.

Is it okay for you to close this issue now?

**Comment by wimrijnders** [comment]
Yes, everything is working now. I am happy to close the issue.

Thank you for your quick response, I truly appreciate it.

This is where the hacking begins! I hope that next time I can deliver a more substantial issue. This was just beginner stuff. Kind regards!
