### ISSUE TITLE
test_signal.py: Rotate test always selects the mul alu rotate

### ISSUE THREAD

**Issue by wimrijnders** [Idein/py-videocore6#45]
Hi there,

I believe the following is incorrect:

[Source](https://github.com/Idein/py-videocore6/blob/23b49938a1500a4041519c1079a5faeb37976f44/tests/test_signals.py#L150):

```py
        if i % 1 == 0:
            rotate(r1, r0, i)       # add alias
        else:
            nop().rotate(r1, r0, i) # mul alias
```

`i % 1` will always return 1, therefore the condition is always false and the mul alias branch is always selected.
I think it should be `i % 2`, so that add alias and mul alias are alternately outputted, which seems to be the intent here.

Do you agree?

**Comment by wimrijnders** [comment]
Actually, I believe it would be better to have separate loops for the add alu and mul alu, so that the test is complete.
Same goes for the next loop, where the rotate value comes from register `r5` instead of a small immediate.

**Comment by notogawa** [comment]
Thank you for your reporting. We will fix it.

**Comment by wimrijnders** [comment]
My pleasure!

**Comment by wimrijnders** [comment]
That was quick! Pulling and testing right away.

**Comment by wimrijnders** [comment]
Working!

However, I see something interesting: the output for `rotate(r1, r0, i)` (add alias) is the same as `nop().rotate(r1, r0, i)` (mul alias). In both cases, the mul ALU is used.

Perhaps it is the case that rotate only works via the mul ALU?

**Comment by Terminus-IMRC** [comment]
Yes, rotate only works on mul ALU as in VC4 QPU.

**Comment by wimrijnders** [comment]
Thank you for the confirmation! And thank you for the extremely quick fix.
