### ISSUE TITLE
Update README.md to include drm v3d incompatible with armv8 systems

### ISSUE THREAD

**Issue by kovaszab** [Idein/py-videocore6#52]
Hi guys! I recently tried to make this work with an armv8 os. I could load the kernel modules ```vc4``` and ```v3d``` set the ```dtoverlay=vc4-kms-v3d-pi4``` or ```dtoverlay=vc4-fkms-v3d``` in ```config.txt``` without problems, but ```/dev/dri/card``` is still not shown. No problems with armv7l os-es though. I think this might be a problem with the drm v3d driver. It looks like 64 bit and v3d are not compatible. Could you guys verify this?

**Comment by Terminus-IMRC** [comment]
Thank you for the interest!

However, I could not reproduce your issue with the latest 64-bit Raspberry Pi OS ([2021-05-07-raspios-buster-arm64-lite](http://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-05-28/)).
Could you ensure that your board is supported by py-videocore6 (Pi 4 or Pi 400), and could you try to reproduce the problem with the latest Raspberry Pi OS?

**Comment by kovaszab** [comment]
My bad. I should have checked with Raspbian before issuing. I only tried it with Alpine on aarch64. I guess then it's just another `mdev` bug/misbehaviour. I have succesfully made py-videocore6 work on a handful of OS-es, but none of them was 64-bit, hence the conclusion that it won't work on 64-bit. Also a reference on the Gentoo wiki kinda misleaded me [https://wiki.gentoo.org/wiki/Raspberry_Pi_VC4#Is_it_working.3F](https://wiki.gentoo.org/wiki/Raspberry_Pi_VC4#Is_it_working.3F)

**Comment by Terminus-IMRC** [comment]
Don't worry about that. So you succeeded to confirm that py-videocore6 works on aarch64? Is it good for you to close this issue?

**Comment by kovaszab** [comment]
Yes, thank you very much!
